### ISSUE TITLE
April Fools Issue

### ISSUE THREAD

**Issue by 0xPoly** [systemdaemon/systemd#1] opened 2015-03-30 12:15 UTC
This repo has been put up 2 days early. Please fix.

**Comment by 7heo** [comment] 2015-03-30 13:36
I experience the issue here too.

**Comment by zeflap** [comment] 2015-03-30 14:13
Confirming this one, as well.

**Comment by it0a** [comment] 2015-03-30 15:55
Also confirming. Please fix ASAP

**Comment by Munchotaur** [comment] 2015-03-30 16:58
Same here. Please fix before 2038 so we don't experience the Great Date Bug any earlier than necessary.

**Comment by X39** [comment] 2015-03-30 19:09
anyone considered that just the date from one of the devs is not set correctly?
most likely they just thought "hey its 1. april" and missed that their computer somehow messed it up because of idk ...
tried to get creative
failed

**Comment by systemdaemon** [comment] 2015-03-30 20:49
As with all reported systemd issues, this one is functioning as designed. wontfix

**Closed as completed by systemdaemon** 2015-03-30 20:49 UTC

**Comment by LastSioux** [comment] 2015-03-31 17:52
It's about time zone, sun rises there 3 days earlier.
